apiVersion: v1
kind: Service
# Sets the meta data
metadata:
    name: sd-exercise
# Here the type of service is set as “LoadBalancer”. 
# This means that the Kubernetes cluster should automatically provision an external load balancer that distributes incoming traffic across the service's pods
spec:
    type: LoadBalancer
    # The ports that the service should open are configured here
    ports:
    - port: 3000 
    selector:
        app: sd-exercise
